### ISSUE TITLE
No bc1 addresses being parsed?

### ISSUE THREAD

**Issue by Goro2030** [gcarq/rusty-blockparser#63]
I've noticed that when running the new "Balances" callback, I get no bc1 address in the output file. Is that because you consider all bc1's as 3x's , or because you can't parse them yet?

Also, another question about Balances ... which is the rationale of how the addresses are sorted in the output file? It's definitively not by balance, and doesn't seem to either be by "last day seen or used".

**Comment by gcarq** [comment]
Addresses starting with bc1 are bech32 addresses, which are not supported on the master branch yet. However I'm working on this right now in #62. Its still WIP because right now it only supports bitcoin and there are still some code quirks to fix. That being said it should be fully functional for BTC.

The balances are not sorted, but something like `sort --field-separator=';' --key=2 <file>` should do it

**Comment by Goro2030** [comment]
I saw your fork for changing the "engine", that'd be great, as more and more "BTC" is stored in bench32 addresses. Thanks for doing this! I just wish I knew rusty to be able to help more. I'll provide "cosmetic" pull requests, maybe on the documentation side if you allow me to as that's what I do :)

Thanks for the sorting question. I know how to sort the file, was just wondering if you had any logic in the code itself, which it didn't appear as so. I was right :) Thanks for clarifying.

**Comment by gcarq** [comment]
That would be awesome! Feel free to send pull requests :)

**Comment by gcarq** [comment]
Bech32 address support has been implemented with 0.9.0
